version: '1.0'

services:
  project:
    build: ./
    container_name: 'mission-project'
    networks:
      - mission-gateway_mission
      - mission-db_postgres
    ports:
      - 8083:80
    environment:
      POSTGRES_HOST: mission-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: mission-postgres
      POSTGRES_SCHEMA: public
      POSTGRES_PASSWORD: private_password
      POSTGRES_USERNAME: postgres
      APPLICATION_PORT: 80
      PROFILE_URL: http://profile
networks:
  mission-gateway_mission:
    external: true
  mission-db_postgres:
    external: true