### Создание проекта
POST http://localhost:80/project/private/admin/create
Content-Type: application/json

{
  "title": "tit3le",
  "description": "description"
}

### Поиск проекта по id
GET http://localhost:80/project/private/admin/find?id=f886730375004f82aa33e6c114f5d305

### Закрепить команду за проектом
POST http://localhost:80/project/private/admin/attach
Content-Type: application/json

{
  "project": "f886730375004f82aa33e6c114f5d305",
  "participants": [
    "id",
    "id2"
  ]
}

### Поиск команды по id проекта
GET http://localhost:80/project/private/admin/team?project=f886730375004f82aa33e6c114f5d305

### Изменить роль участника команды
POST http://localhost:80/project/private/admin/role
Content-Type: application/json

{
  "projectId": "f886730375004f82aa33e6c114f5d305",
  "userId": "id2",
  "role": "LEADER"
}

### Изменить Стадию проекта
POST http://localhost:80/project/private/admin/stage
Content-Type: application/json

{
  "projectId": "ffe5b5301fcf4977a73d61072d5c2ba4",
  "stage": "FINISHING"
}

### Получить стадию проекта
GET http://localhost:80/project/private/admin/stage?project=ffe5b5301fcf4977a73d61072d5c2ba4

### Получить историю изменения стадии
GET http://localhost:80/project/private/admin/stage/history?project=ffe5b5301fcf4977a73d61072d5c2ba4

### Создать задачу проекту
POST http://localhost:80/project/private/admin/task/create
Content-Type: application/json

{
  "projectId": "b84005cee5424b1297c44642b4e64c56",
  "title": "FINISHING",
  "text": "text"
}

### Получить список id-задач проекта
GET http://localhost:80/project/private/admin/task/get/all?project=b84005cee5424b1297c44642b4e64c56

### Получить задачу по id
GET http://localhost:80/project/private/admin/task/get?task=73995114d0a8461a9a5f5c359d8f5edc